version: '3'

volumes:
  pg_data_production:
  static_production:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: grishastr/taski_backend
    env_file: .env
    volumes:
      - static_production:/backend_static

  frontend:
    image: grishastr/taski_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_production:/frontend_static

  gateway:
    image: grishastr/taski_gateway
    env_file: .env
    volumes:
      - static_production:/staticfiles
    ports:
      - 8000:80