version: '3'

volumes:
  taski_pg_data_production:
  taski_static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - taski_pg_data_production:/var/lib/postgresql/data
  backend:
    image: grishastr/taski_backend
    env_file: .env
    volumes:
      - taski_static_volume:/backend_static
  frontend:
    image: grishastr/taski_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - taski_static_volume:/frontend_static
  gateway:
    image: grishastr/taski_gateway
    env_file: .env
    volumes:
      - taski_static_volume:/staticfiles/
    ports:
      - 8000:80
